package ffm.geok.com.javagen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ffm.geok.com.model.FireDateEntity;
import ffm.geok.com.model.FireCheckEntity;
import ffm.geok.com.model.FireMediaEntity;

import ffm.geok.com.javagen.FireDateEntityDao;
import ffm.geok.com.javagen.FireCheckEntityDao;
import ffm.geok.com.javagen.FireMediaEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fireDateEntityDaoConfig;
    private final DaoConfig fireCheckEntityDaoConfig;
    private final DaoConfig fireMediaEntityDaoConfig;

    private final FireDateEntityDao fireDateEntityDao;
    private final FireCheckEntityDao fireCheckEntityDao;
    private final FireMediaEntityDao fireMediaEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fireDateEntityDaoConfig = daoConfigMap.get(FireDateEntityDao.class).clone();
        fireDateEntityDaoConfig.initIdentityScope(type);

        fireCheckEntityDaoConfig = daoConfigMap.get(FireCheckEntityDao.class).clone();
        fireCheckEntityDaoConfig.initIdentityScope(type);

        fireMediaEntityDaoConfig = daoConfigMap.get(FireMediaEntityDao.class).clone();
        fireMediaEntityDaoConfig.initIdentityScope(type);

        fireDateEntityDao = new FireDateEntityDao(fireDateEntityDaoConfig, this);
        fireCheckEntityDao = new FireCheckEntityDao(fireCheckEntityDaoConfig, this);
        fireMediaEntityDao = new FireMediaEntityDao(fireMediaEntityDaoConfig, this);

        registerDao(FireDateEntity.class, fireDateEntityDao);
        registerDao(FireCheckEntity.class, fireCheckEntityDao);
        registerDao(FireMediaEntity.class, fireMediaEntityDao);
    }
    
    public void clear() {
        fireDateEntityDaoConfig.clearIdentityScope();
        fireCheckEntityDaoConfig.clearIdentityScope();
        fireMediaEntityDaoConfig.clearIdentityScope();
    }

    public FireDateEntityDao getFireDateEntityDao() {
        return fireDateEntityDao;
    }

    public FireCheckEntityDao getFireCheckEntityDao() {
        return fireCheckEntityDao;
    }

    public FireMediaEntityDao getFireMediaEntityDao() {
        return fireMediaEntityDao;
    }

}
