package ffm.geok.com.javagen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import ffm.geok.com.model.FireDateEntity;

import ffm.geok.com.javagen.FireDateEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fireDateEntityDaoConfig;

    private final FireDateEntityDao fireDateEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fireDateEntityDaoConfig = daoConfigMap.get(FireDateEntityDao.class).clone();
        fireDateEntityDaoConfig.initIdentityScope(type);

        fireDateEntityDao = new FireDateEntityDao(fireDateEntityDaoConfig, this);

        registerDao(FireDateEntity.class, fireDateEntityDao);
    }
    
    public void clear() {
        fireDateEntityDaoConfig.clearIdentityScope();
    }

    public FireDateEntityDao getFireDateEntityDao() {
        return fireDateEntityDao;
    }

}
