package ffm.geok.com.javagen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import ffm.geok.com.model.FireCheckEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FIRE_CHECK_ENTITY".
*/
public class FireCheckEntityDao extends AbstractDao<FireCheckEntity, String> {

    public static final String TABLENAME = "FIRE_CHECK_ENTITY";

    /**
     * Properties of entity FireCheckEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Confirmor = new Property(1, String.class, "confirmor", false, "CONFIRMOR");
        public final static Property Fireid = new Property(2, String.class, "fireid", false, "FIREID");
        public final static Property Isfire = new Property(3, String.class, "isfire", false, "ISFIRE");
        public final static Property Moditime = new Property(4, String.class, "moditime", false, "MODITIME");
        public final static Property Remark = new Property(5, String.class, "remark", false, "REMARK");
    }


    public FireCheckEntityDao(DaoConfig config) {
        super(config);
    }
    
    public FireCheckEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FIRE_CHECK_ENTITY\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"CONFIRMOR\" TEXT," + // 1: confirmor
                "\"FIREID\" TEXT," + // 2: fireid
                "\"ISFIRE\" TEXT," + // 3: isfire
                "\"MODITIME\" TEXT," + // 4: moditime
                "\"REMARK\" TEXT);"); // 5: remark
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FIRE_CHECK_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FireCheckEntity entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String confirmor = entity.getConfirmor();
        if (confirmor != null) {
            stmt.bindString(2, confirmor);
        }
 
        String fireid = entity.getFireid();
        if (fireid != null) {
            stmt.bindString(3, fireid);
        }
 
        String isfire = entity.getIsfire();
        if (isfire != null) {
            stmt.bindString(4, isfire);
        }
 
        String moditime = entity.getModitime();
        if (moditime != null) {
            stmt.bindString(5, moditime);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(6, remark);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FireCheckEntity entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String confirmor = entity.getConfirmor();
        if (confirmor != null) {
            stmt.bindString(2, confirmor);
        }
 
        String fireid = entity.getFireid();
        if (fireid != null) {
            stmt.bindString(3, fireid);
        }
 
        String isfire = entity.getIsfire();
        if (isfire != null) {
            stmt.bindString(4, isfire);
        }
 
        String moditime = entity.getModitime();
        if (moditime != null) {
            stmt.bindString(5, moditime);
        }
 
        String remark = entity.getRemark();
        if (remark != null) {
            stmt.bindString(6, remark);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public FireCheckEntity readEntity(Cursor cursor, int offset) {
        FireCheckEntity entity = new FireCheckEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // confirmor
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // fireid
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // isfire
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // moditime
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // remark
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FireCheckEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setConfirmor(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFireid(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIsfire(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setModitime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setRemark(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final String updateKeyAfterInsert(FireCheckEntity entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(FireCheckEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FireCheckEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
