package ffm.geok.com.javagen;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import ffm.geok.com.model.FireDateEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FIRE_DATE_ENTITY".
*/
public class FireDateEntityDao extends AbstractDao<FireDateEntity, String> {

    public static final String TABLENAME = "FIRE_DATE_ENTITY";

    /**
     * Properties of entity FireDateEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Type = new Property(1, String.class, "type", false, "TYPE");
        public final static Property Lat = new Property(2, Double.class, "lat", false, "LAT");
        public final static Property Lon = new Property(3, Double.class, "lon", false, "LON");
        public final static Property Province = new Property(4, String.class, "province", false, "PROVINCE");
        public final static Property City = new Property(5, String.class, "city", false, "CITY");
        public final static Property County = new Property(6, String.class, "county", false, "COUNTY");
        public final static Property CreateTime = new Property(7, String.class, "createTime", false, "CREATETIME");
        public final static Property FindTime = new Property(8, String.class, "findTime", false, "FINDTIME");
        public final static Property UpdateTime = new Property(9, String.class, "updateTime", false, "UPDATETIME");
        public final static Property Satellite = new Property(10, String.class, "satellite", false, "SATELLITE");
        public final static Property See = new Property(11, String.class, "see", false, "SEE");
    }


    public FireDateEntityDao(DaoConfig config) {
        super(config);
    }
    
    public FireDateEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FIRE_DATE_ENTITY\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"TYPE\" TEXT," + // 1: type
                "\"LAT\" REAL," + // 2: lat
                "\"LON\" REAL," + // 3: lon
                "\"PROVINCE\" TEXT," + // 4: province
                "\"CITY\" TEXT," + // 5: city
                "\"COUNTY\" TEXT," + // 6: county
                "\"CREATETIME\" TEXT," + // 7: createTime
                "\"FINDTIME\" TEXT," + // 8: findTime
                "\"UPDATETIME\" TEXT," + // 9: updateTime
                "\"SATELLITE\" TEXT," + // 10: satellite
                "\"SEE\" TEXT);"); // 11: see
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FIRE_DATE_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, FireDateEntity entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(2, type);
        }
 
        Double lat = entity.getLat();
        if (lat != null) {
            stmt.bindDouble(3, lat);
        }
 
        Double lon = entity.getLon();
        if (lon != null) {
            stmt.bindDouble(4, lon);
        }
 
        String province = entity.getProvince();
        if (province != null) {
            stmt.bindString(5, province);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(6, city);
        }
 
        String county = entity.getCounty();
        if (county != null) {
            stmt.bindString(7, county);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(8, createTime);
        }
 
        String findTime = entity.getFindTime();
        if (findTime != null) {
            stmt.bindString(9, findTime);
        }
 
        String updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindString(10, updateTime);
        }
 
        String satellite = entity.getSatellite();
        if (satellite != null) {
            stmt.bindString(11, satellite);
        }
 
        String see = entity.getSee();
        if (see != null) {
            stmt.bindString(12, see);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, FireDateEntity entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String type = entity.getType();
        if (type != null) {
            stmt.bindString(2, type);
        }
 
        Double lat = entity.getLat();
        if (lat != null) {
            stmt.bindDouble(3, lat);
        }
 
        Double lon = entity.getLon();
        if (lon != null) {
            stmt.bindDouble(4, lon);
        }
 
        String province = entity.getProvince();
        if (province != null) {
            stmt.bindString(5, province);
        }
 
        String city = entity.getCity();
        if (city != null) {
            stmt.bindString(6, city);
        }
 
        String county = entity.getCounty();
        if (county != null) {
            stmt.bindString(7, county);
        }
 
        String createTime = entity.getCreateTime();
        if (createTime != null) {
            stmt.bindString(8, createTime);
        }
 
        String findTime = entity.getFindTime();
        if (findTime != null) {
            stmt.bindString(9, findTime);
        }
 
        String updateTime = entity.getUpdateTime();
        if (updateTime != null) {
            stmt.bindString(10, updateTime);
        }
 
        String satellite = entity.getSatellite();
        if (satellite != null) {
            stmt.bindString(11, satellite);
        }
 
        String see = entity.getSee();
        if (see != null) {
            stmt.bindString(12, see);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public FireDateEntity readEntity(Cursor cursor, int offset) {
        FireDateEntity entity = new FireDateEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // type
            cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2), // lat
            cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3), // lon
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // province
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // city
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // county
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // createTime
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // findTime
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // updateTime
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // satellite
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11) // see
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, FireDateEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setType(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setLat(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
        entity.setLon(cursor.isNull(offset + 3) ? null : cursor.getDouble(offset + 3));
        entity.setProvince(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCity(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCounty(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setCreateTime(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setFindTime(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setUpdateTime(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setSatellite(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setSee(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
     }
    
    @Override
    protected final String updateKeyAfterInsert(FireDateEntity entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(FireDateEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(FireDateEntity entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
